name: build

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4.2.2

      - run: ./build.sh

      - uses: softprops/action-gh-release@v2.0.6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*.png"
          fail_on_unmatched_files: true

      - uses: softprops/action-gh-release@v2.0.6
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          files: "*.png"
          fail_on_unmatched_files: true
          prerelease: true
          tag_name: nightly-${{ github.sha }}
