name: build

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4.2.2

      - run: |
          mkdir .bin
          cd .bin

          # depName=RazrFalcon/resvg
          RESVG_VERSION="v0.45.1"

          wget "https://github.com/RazrFalcon/resvg/releases/download/${RESVG_VERSION}/resvg-linux-x86_64.tar.gz"
          tar xf resvg-linux-x86_64.tar.gz

          cd ..

          export PATH="$PATH:$(pwd)/.bin"
          ./build.sh

      - if: startsWith(github.ref, 'refs/tags/')
        run: |
          zip -r "otakuworkshare-branding-${GITHUB_REF#refs/tags/}.zip" *.png

      - if: "! startsWith(github.ref, 'refs/tags/')"
        run: |
          zip -r "otakuworkshare-branding-$GITHUB_SHA.zip" *.png

      - uses: softprops/action-gh-release@v2.2.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*.zip"
          fail_on_unmatched_files: true

      - uses: softprops/action-gh-release@v2.2.2
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          files: "*.zip"
          fail_on_unmatched_files: true
          prerelease: true
          tag_name: nightly-${{ github.sha }}
